# NumPy Indexing and Selection


In [1]:
import numpy as np


In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [8]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
new_arr = arr[0:5]
print(new_arr)

eight = arr[7]
print(eight)

[1 2 3 4 5]
8


In [9]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [11]:
sentence = np.array(['I', 'love', 'Python', 'very', 'much'])
print(sentence)

# get first two elements
print(sentence[:2])

['I' 'love' 'Python' 'very' 'much']
['I' 'love']


In [16]:
#  2d array access
nums = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(nums)

print(arr)

# access first row
print(f'First row: {arr[0]}')

# access first column
print(f'First column: {arr[:, 0]}')

# access second row
print(f'Second row: {arr[1]}')

# access second column
print(f'Second column: {arr[:, 1]}')


[[1 2 3]
 [4 5 6]
 [7 8 9]]
First row: [1 2 3]
First column: [1 4 7]
Second row: [4 5 6]
Second column: [2 5 8]
