# NumPy Indexing and Selection


In [1]:
import numpy as np


In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [8]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
new_arr = arr[0:5]
print(new_arr)

eight = arr[7]
print(eight)

[1 2 3 4 5]
8


In [9]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [11]:
sentence = np.array(['I', 'love', 'Python', 'very', 'much'])
print(sentence)

# get first two elements
print(sentence[:2])

['I' 'love' 'Python' 'very' 'much']
['I' 'love']
