In [1]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)

[1 2 3 4 5]


In [2]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(np.array(my_mat))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(np.arange(0, 10, 2))


[0 2 4 6 8]


In [4]:
print(np.ones(3))

[1. 1. 1.]


In [6]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])