In [1]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)

[1 2 3 4 5]


In [2]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(np.array(my_mat))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(np.arange(0, 10, 2))


[0 2 4 6 8]


In [4]:
print(np.ones(3))

[1. 1. 1.]


In [6]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# linspace returns evenly spaced numbers over a specified interval(start, stop, number of points to generate)
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [8]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
# random numbers
np.random.rand(5)

array([0.12247774, 0.26560381, 0.60167724, 0.95100989, 0.4163122 ])

In [10]:
# radn returns a sample from the standard normal distribution centered around 0
np.random.randn(2, 4)

array([[-0.26981702,  0.27423487,  1.15943194, -1.71242186],
       [ 0.12492902,  0.11746129,  0.60738828,  3.15928404]])

In [11]:
# randint returns random integers from low to high
np.random.randint(1, 100, 10)


array([79, 80, 98, 25,  9, 77, 49, 74, 88, 73])

In [12]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)
print(ranarr)

[ 1 15 23  4 47  8  9 37 33 42]


In [13]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
# max
print(ranarr.max())

# min
print(ranarr.min())

#argmax returns the index of the max value
print(ranarr.argmax())

# argmin returns the index of the min value
print(ranarr.argmin())

47
1
4
0


In [19]:
arr.shape

(25,)

In [22]:
arr = arr.reshape(5, 5)
# now check shape
arr.shape

(5, 5)

In [23]:
arr.dtype

dtype('int64')